fix: Avoid crash during Hestia install (#5223)
* fix: Avoid crash during Hestia install

Because of commit #5218, the Hestia installation fails as the self-signed certificate is not created.

```
[ * ] Adding SSL certificate to Hestia Control Panel...
sed: -e expression #1, char 3: unexpected `,'
sed: -e expression #1, char 1: unknown command: `,'
[ * ] Enabling SFTP jail...
[...]
[ * ] Configuring System IP...
Job for apache2.service failed because the control process exited with error code.
See "systemctl status apache2.service" and "journalctl -xeu apache2.service" for details.
Error: apache2 restart failed
Error: can't create test.example.net domain
```

This is because commit #5218 is quoting the variables in the following validations:

```
is_common_format_valid "$state" "state"
is_common_format_valid "$org" "org"
is_common_format_valid "$unit" "unit"
```
State, Organization, and Unit variables can contain (and in this case contain) spaces, so they fail validation and the certificate is not created, causing the crash.

- This PR removes those validations in script `v-generate-ssl-cert`
- Added missing quotes to variable expansion in v-list-backup-host to prevent word splitting.
- It also refined validation logic in `v-change-user-name` by checking first and last names independently.

* Add space-aware common format validator

Introduce a new common format validation function that safely allows spaces and apply it to relevant fields requiring space support.