Fix few small bugs related to host ssl (#2922)
* Fix issue when ssl for domain allready exists 

It seems USER_DATA was not properly loaded

root@dev:/usr/local/hestia/ssl# v-add-letsencrypt-host 
cat: /usr/local/hestia/data/users//user.conf: No such file or directory
grep: /usr/local/hestia/data/users//web.conf: No such file or directory
grep: /usr/local/hestia/data/users//web.conf: No such file or directory
grep: /usr/local/hestia/data/users//web.conf: No such file or directory
Error: nginx restart failed
Error: nginx restart failed
Error: Let's Encrypt SSL creation failed

* No need to restart web / proxy service

Only Hestia, mail and ftp get updated

* Fix bug for modphp setups