fix
+ bash install/hst-install-ubuntu.sh --hostname hestia.local.test --email admin@example.com --username admin --password Password123 --interactive no --force --with-debs /tmp/hestiacp-src/deb --clamav no --spamassassin no
TERM environment variable not set.
Welcome to the Hestia Control Panel installer!

Please wait, the installer is now checking for missing dependencies...

[ * ] Installing dependencies...

Installation aborted
====================================================================
ERROR: Install script version does not match package version!
Please download the installer from the release branch in order to continue:

https://raw.githubusercontent.com/hestiacp/hestiacp/release/install/hst-install.sh

To test pre-release versions, build the .deb packages and re-run the installer:
  ./hst_autocompile.sh --hestia branchname no
  ./hst-install.sh .. --with-debs /tmp/hestiacp-src/debs

Error: Installation aborted
Error: Process completed with exit code 1.