Staging/1.6.9 (#2952)
* Fix issue with incorrect merge

* Fix bug v-change-web-domain-name

* Fix Quick installer issues (#2921)

* Some rare cases version might be empty

* Remove debug info

* If admin is not created status is not set

* Return correct status code

* Fix docuwiki installer

Install dir got changed due to new version

* Update to 2022-07-31a

See CVE-2022-3123

* Update opencart

* Use correct folder

* Update prestashop

* Fix few small bugs related to host ssl (#2922)

* Fix issue when ssl for domain allready exists

It seems USER_DATA was not properly loaded

root@dev:/usr/local/hestia/ssl# v-add-letsencrypt-host
cat: /usr/local/hestia/data/users//user.conf: No such file or directory
grep: /usr/local/hestia/data/users//web.conf: No such file or directory
grep: /usr/local/hestia/data/users//web.conf: No such file or directory
grep: /usr/local/hestia/data/users//web.conf: No such file or directory
Error: nginx restart failed
Error: nginx restart failed
Error: Let's Encrypt SSL creation failed

* No need to restart web / proxy service

Only Hestia, mail and ftp get updated

* Fix bug for modphp setups

* Merge pull request #2924 from jaapmarcus/fix/allow-more-chars-for-name

is_name_format_valid is only used for the name

* Merge pull request #2925 from hestiacp/jaapmarcus-patch-1

When restart is not set it should reload instead restart

* 2788 [Bug] Quick install Wordpress other languages then EN (#2818)

* Update changelog [CI SKIP]

[CI SKIP]

* updated jquery to v3.6.1 (#2932)

* Update changelog

* Fix #2943 for release branch

* Update changelog

* Update version

* Quick installer: Use the MediaWiki 1.38.4 (#2948)

See https://lists.wikimedia.org/hyperkitty/list/mediawiki-announce@lists.wikimedia.org/thread/DMQKMFSH4K7KLBXWZTDBGI2PWLLHJHJZ/

* Add support for Kurdish Sorani

@qezwan

* php version bump

* Add check if email is valid (#2944)

* Allow the use of (#2951)

v-add-remote-dns-host dev.xxxx.xxx 8083 'xxxxxxxx' '' '' "newuser"

* Add support for Kurdish Sorani (#2945)

@qezwan

* Fix v-add-backup-host for sftp servers with different login prompt (#2950)

* Fix v-add-backup-host for sftp server that outputs different password prompt

On FreeBSD hosted sftp server, the password prompt looks something like this: "Password for: user@host:". This case was not handled so far.

* Fix sftp backup procedure for servers with different login prompt

* Update changelog

* Small changes Changelog

[skip_ci]

* Update versions

Co-authored-by: Raphael <rs@scit.ch>
Co-authored-by: Alber Khan <39749258+4183r@users.noreply.github.com>
Co-authored-by: Zoran Dori <zorandori4444@gmail.com>
Co-authored-by: Ice Lake <30789544+istiak101@users.noreply.github.com>