hestia: Fix config path DB and DNS tool sanity checks
Issue:
The command `v-delete-remote-dns-host mydnshost.example.com` does not work as expected and returns

```
grep: /usr/local/hestia/data/users/admin/../../conf/dns-cluster.conf: No such file or directory
Error: dns-cluster host mydnshost.example.com doesn't exist
```

This is caused by this check:
https://github.com/hestiacp/hestiacp/blob/7803685957b50c58800965f32e8823a3e5bf7f4d/bin/v-delete-remote-dns-host#L33

Mostly because "HOST" would always check for
`$HESTIA/data/users/$user/$1.conf`
in https://github.com/hestiacp/hestiacp/blob/7803685957b50c58800965f32e8823a3e5bf7f4d/func/main.sh#L339

but the file is located in `/usr/local/hestia/conf/dns-cluster.conf`, not `/usr/local/hestia/data/(users/admin/../../)conf/dns-cluster.conf`.
A fix would be to add an additional `..` to the path, similiar to https://github.com/hestiacp/hestiacp/blob/7803685957b50c58800965f32e8823a3e5bf7f4d/bin/v-add-database#L58

Upon further research we discovered additional sanity checks that used the wrong path in the DNS as well as the DB toolset.
They were confirmed to be broken beforehand and to be fixed afterwards by using the following commands:

```
v-list-database-host mysql localhost
v-delete-remote-dns-host mydnshost.example.com
```