unicode characters in shell arguments (composer solution) (#2720)
* unicode characters in shell arguments (composer solution)

a composer-based alternative to PR https://github.com/hestiacp/hestiacp/pull/2717

* linter fix

Fatal error: Namespace declaration statement has to be the very first statement or after any declare call in the script in ./web/src/app/System/HestiaApp.php on line 6 Errors parsing ./web/src/app/System/HestiaApp.php

* Move to Hestia controlled repo

+ Fix 1 missing escapeshellargs

Co-authored-by: Jaap Marcus <9754650+jaapmarcus@users.noreply.github.com>